---
title: "Blog"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load in libraries, amke sure all are needed
library(tidyverse)
library(ggplot2)
library(here)
library(lubridate)
library(forecast)
library(MLmetrics)
library(tsibble)
library(astsa)
library(janitor)
library(feasts)
```

Load in Honolii Sea Surface Temperature Data using here package

```{r, results='hide'}
sst_honolii_1985_2021 <- read.csv(here("data", "sst_honolii_1985_2021.csv" ))
sst_honolii_1985_2021
```


Clean Data

```{r, results='hide'}
sst_honolii_1985_2021 <- sst_honolii_1985_2021 %>% 
  select(time, CRW_SST) %>% 
  mutate(time = as.Date(time))
sst_honolii_1985_2021
```

Determine SST Monthly Means
```{r, results='hide'}
sst_honolii_1985_2021_month <- sst_honolii_1985_2021 %>% 
  mutate(time = floor_date(time, "month")) %>% 
  group_by(time) %>% 
  summarise(mean_sst = mean(CRW_SST))

sst_honolii_1985_2021_month
```

Plot Data

```{r}
sst_honolii_1985_2021_month_plot <- ggplot(data = sst_honolii_1985_2021_month, aes(x = time, y = mean_sst)) +
  geom_line()

sst_honolii_1985_2021_month_plot
```

Look for trend using a linear regression

```{r}
sst_honolii_1985_2021_month_regression <- sst_honolii_1985_2021_month_plot +
  geom_smooth(method="lm", col="black")

sst_honolii_1985_2021_month_regression
```
```{r}
ols1 <- lm(mean_sst ~ time, data = sst_honolii_1985_2021_month)
ols1
summary(ols1)
```



Convert dataframe into a time series
```{r, results='hide'}
sst_honolii_1985_2021_month_ts <- ts(sst_honolii_1985_2021_month$mean_sst, start = c(1985, 11), frequency = 12)

sst_honolii_1985_2021_month_ts
```


Run a classical decomposition model

```{r}
as_tsibble(sst_honolii_1985_2021_month_ts) %>%
  model(
    classical_decomposition(value, type = "additive")
  ) %>%
  components() %>%
  autoplot() +
  labs(title = "Classical additive decomposition")
```


```{r, results='hide'}
sst_honolii_1985_2021_month_tsibble <- sst_honolii_1985_2021_month_ts %>% as_tsibble() 

sst_honolii_1985_2021_month_tsibble
```

```{r}
sst_honolii_1985_2021_month_tsibble %>% 
  gg_season(value)
```
```{r}
sst_honolii_1985_2021_month_tsibble %>% 
  gg_subseries(value)
```
```{r, results='hide'}
dcmp <- sst_honolii_1985_2021_month_tsibble %>%
  model(stl = STL(value))
components(dcmp)
```
```{r}
components(dcmp) %>%
  as_tsibble() %>%
  autoplot(value, colour="gray") +
  geom_line(aes(y=trend), colour = "#D55E00")
```


Forecasting 

DSHW 


```{r}
training=window(sst_honolii_1985_2021_month_ts, start = c(1985,11), end = c(2018,11))
validation=window(sst_honolii_1985_2021_month_ts, start = c(2018,11), end = c(2021,10))
```



```{r}
dshw_model = dshw(training, period1=4, period2 = 12, h=length(validation))
MAPE(dshw_model$mean, validation)*100

dshw_model

dshw_plot <-plot(sst_honolii_1985_2021_month_ts, col="blue", xlab="Day", ylab="SST", main="DSHW Forecast", type='l')
lines(dshw_model$mean, col="red", lwd=2)
```


```{r}
dshw_model_2 = dshw(training, period1=12, period2 =72, h = 72)

dshw_model_2


fcst_dshw <- forecast(dshw_model_2, h = 50)
autoplot(fcst_dshw, include = 220)
print(summary(fcst_dshw))
```










ARIMA

```{r}
arima_training <- window(sst_honolii_1985_2021_month_ts, start = c(1985,11), end = c(2018,11))

fit_arima_training <- auto.arima(arima_training, d = 1, D = 1, stepwise = FALSE, approximation = FALSE, trace = TRUE)
print(summary(fit_arima_training))
checkresiduals(fit_arima_training)
```
```{r}
fcst_arima <- forecast(fit_arima_training, h = 146, find.frequency = TRUE)
autoplot(fcst_arima, include = 120)
print(summary(fcst_arima))
```
```{r}
sst_honolii_2014_2021_month <- sst_honolii_1985_2021_month %>% 
  filter(time > '2014-11-08')




sst_honolii_2014_2021_month_plot <- ggplot(data = sst_honolii_2014_2021_month, aes(x = time, y = mean_sst)) +
  geom_line()

sst_honolii_1985_2021_month_plot

sst_honolii_2014_2021_month_regression <- sst_honolii_2014_2021_month_plot +
  geom_smooth(method="lm", col="black")

sst_honolii_2014_2021_month_regression

```
```{r}
ols <- lm(mean_sst ~ time, data = sst_honolii_2014_2021_month)
ols
summary(ols)
```



