---
title: "model_date_testing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(here)
library(lubridate)
library(forecast)
library(MLmetrics)
library(tsibble)
library(astsa)
library(janitor)
library(feasts)
```




```{r}
sst_honolii_1985_2021 <- read.csv(here("data", "sst_honolii_1985_2021.csv" ))
sst_honolii_1985_2021
```




```{r}
sst_honolii_1985_2021 <- sst_honolii_1985_2021 %>% 
  select(time, CRW_SST)

sst_honolii_1985_2021
```


```{r}
sst_honolii_1985_2021 <- sst_honolii_1985_2021 %>%
mutate(time = as.Date(time))
sst_honolii_1985_2021
```

```{r}
#months(sst_honolii_1985_2021$time)
```


```{r}
sst_honolii_1985_2021_month <- sst_honolii_1985_2021 %>% 
  mutate(time = floor_date(time, "month")) %>% 
  group_by(time) %>% 
  summarise(mean_sst = mean(CRW_SST))

sst_honolii_1985_2021_month
```


```{r}
sst_honolii_1985_2021_month_plot <- ggplot(data = sst_honolii_1985_2021_month, aes(x = time, y = mean_sst)) +
  geom_line()

sst_honolii_1985_2021_month_regression <- sst_honolii_1985_2021_month_plot +
  geom_smooth(method="lm", col="black")

sst_honolii_1985_2021_month_regression

```

```{r}
sst_honolii_1985_2021_month_ts <- ts(sst_honolii_1985_2021_month$mean_sst, start = c(1985, 11), frequency = 12)

sst_honolii_1985_2021_month_ts
```



```{r}
training=window(sst_honolii_1985_2021_month_ts, start = c(1985,11), end = c(2018,11))
validation=window(sst_honolii_1985_2021_month_ts, start = c(2018,12), end = c(2021,10))
```



```{r}
dshw_model = dshw(training, period1=6, period2 = 12, h=84)
MAPE(dshw_model$mean, validation)*100

dshw_model

dshw_plot <-plot(sst_honolii_1985_2021_month_ts, col="blue", xlab="Day", ylab="SST", main="DSHW Forecast", type='l')
lines(dshw_model$mean, col="red", lwd=2)
```


```{r}
dshw_model_2 = dshw(training, period1=12, period2 =72, h = 72)

dshw_model_2


fcst_dshw <- forecast(dshw_model_2, h = 50)
autoplot(fcst_dshw, include = 220)
print(summary(fcst_dshw))

```

```{r}
dshw_plot_model_2_fit <-plot(sst_honolii_1985_2021_month_ts, col="blue", xlab="Day", ylab="SST", main="DSHW Forecast", type='l')
lines(dshw_model_2$mean, col="red", lwd=2)
```






```{r}
dshw_model_3 = dshw(training, period1=6, period2 = 36, h = 120)

dshw_model_3

fcst_dshw_3 <- forecast(dshw_model_3, h = 50)
autoplot(fcst_dshw_3, include = 220)
print(summary(fcst_dshw_3))

```





```{r}
fit_arima <- auto.arima(sst_honolii_1985_2021_month_ts, d = 1, D = 1, stepwise = FALSE, approximation = FALSE, trace = TRUE)
print(summary(fit_arima))
checkresiduals(fit_arima)
```

```{r}
fcst <- forecast(fit_arima, h = 120)
autoplot(fcst, include = 180)
print(summary(fcst))
```



```{r}
arima_training <- window(sst_honolii_1985_2021_month_ts, start = c(1985,11), end = c(2018,11))

fit_arima_training <- auto.arima(arima_training, d = 1, D = 1, stepwise = FALSE, approximation = FALSE, trace = TRUE)
print(summary(fit_arima_training))
checkresiduals(fit_arima_training)
```


```{r}
fcst_arima <- forecast(fit_arima_training, h = 146)
autoplot(fcst_arima, include = 60)
print(summary(fcst_arima))
```


```{r}
dshw_model_5 = dshw(training, period1=72, period2 =12, h = 220)

dshw_model_5


fcst_dshw_5 <- forecast(dshw_model_5, h = 50)
autoplot(fcst_dshw_5, include = 220)
print(summary(fcst_dshw_5))
```

```{r}
fit_ets <- ets(sst_honolii_1985_2021_month_ts) 
print(summary(fit_ets))
checkresiduals(fit_ets)
```
```{r}
fcst_ets <- forecast(fit_ets, h = 100)
autoplot(fcst_ets, include = 220)
print(summary(fcst_ets))
```

